apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-custom-nginx
  template:
    metadata:
      labels:
        app: my-custom-nginx
    spec:
      containers:
      - name: my-custom-nginx-container
        image: arunazhagappan/balanced:1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"